# Generated by Django 4.2.16 on 2025-11-03 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this Stripe account', max_length=100)),
                ('api_key', models.CharField(help_text='Stripe API key (encrypted)', max_length=200)),
                ('account_id', models.CharField(blank=True, help_text='Stripe account ID', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Account',
                'verbose_name_plural': 'Stripe Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(help_text='Stripe customer ID', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_created', models.DateTimeField(help_text='Customer created date from Stripe')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stripe_integration.stripeaccount')),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(help_text='Stripe transaction ID', max_length=100, unique=True)),
                ('amount', models.IntegerField(help_text='Amount in cents')),
                ('fee', models.IntegerField(default=0, help_text='Processing fee in cents')),
                ('currency', models.CharField(default='usd', help_text='Currency code (e.g., usd, eur, hkd)', max_length=3)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('pending', 'Pending'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('refund', 'Refund'), ('payout', 'Payout'), ('adjustment', 'Adjustment'), ('fee', 'Fee'), ('transfer', 'Transfer'), ('other', 'Other')], default='charge', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_created', models.DateTimeField(help_text='Transaction date from Stripe')),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stripe_metadata', models.JSONField(blank=True, help_text='Additional metadata from Stripe', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stripe_integration.stripeaccount')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-stripe_created'],
                'indexes': [models.Index(fields=['stripe_id'], name='stripe_inte_stripe__2c4b26_idx'), models.Index(fields=['account', '-stripe_created'], name='stripe_inte_account_8544d9_idx'), models.Index(fields=['status'], name='stripe_inte_status_8b0c3b_idx'), models.Index(fields=['type'], name='stripe_inte_type_145194_idx')],
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(help_text='Stripe subscription ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('paused', 'Paused')], default='active', max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(help_text='Subscription amount in cents')),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('interval', models.CharField(blank=True, help_text='Billing interval (e.g., month, year)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_created', models.DateTimeField(help_text='Subscription created date from Stripe')),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stripe_integration.stripeaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stripe_integration.stripecustomer')),
            ],
            options={
                'verbose_name': 'Stripe Subscription',
                'verbose_name_plural': 'Stripe Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_id'], name='stripe_inte_stripe__a6d205_idx'), models.Index(fields=['status'], name='stripe_inte_status_b13b4e_idx'), models.Index(fields=['customer'], name='stripe_inte_custome_f6dbe0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['stripe_id'], name='stripe_inte_stripe__1793dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['email'], name='stripe_inte_email_1fd9c8_idx'),
        ),
    ]
