# Generated by Django 4.2.16 on 2025-12-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Statement year')),
                ('month', models.IntegerField(help_text='Statement month (1-12)')),
                ('currency', models.CharField(default='hkd', help_text='Currency code (hkd, usd, etc)', max_length=3)),
                ('opening_balance', models.IntegerField(default=0, help_text='Opening balance at start of month (cents)')),
                ('closing_balance', models.IntegerField(default=0, help_text='Closing balance at end of month (cents)')),
                ('gross_revenue', models.IntegerField(default=0, help_text='Total payments + charges (cents)')),
                ('refunds', models.IntegerField(default=0, help_text='Total refunds - negative (cents)')),
                ('net_revenue', models.IntegerField(default=0, help_text='Gross revenue + refunds (cents)')),
                ('processing_fees', models.IntegerField(default=0, help_text='Total Stripe processing fees (cents)')),
                ('activity_balance', models.IntegerField(default=0, help_text='Net revenue - fees (cents)')),
                ('payouts_in_month', models.IntegerField(default=0, help_text='Payouts dated within month - negative (cents)')),
                ('payouts_for_month', models.IntegerField(default=0, help_text="Payouts matched to this month's revenue (cents)")),
                ('calculated_balance', models.IntegerField(default=0, help_text='Calculated closing balance (cents)')),
                ('transaction_count', models.IntegerField(default=0, help_text='Total transactions in month')),
                ('payment_count', models.IntegerField(default=0, help_text='Number of payments/charges')),
                ('payout_count', models.IntegerField(default=0, help_text='Number of payouts')),
                ('refund_count', models.IntegerField(default=0, help_text='Number of refunds')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether balances are reconciled')),
                ('reconciliation_notes', models.TextField(blank=True, help_text='Notes about reconciliation')),
                ('balance_discrepancy', models.IntegerField(default=0, help_text='Difference if not reconciled (cents)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='stripe_integration.stripeaccount')),
            ],
            options={
                'verbose_name': 'Monthly Statement',
                'verbose_name_plural': 'Monthly Statements',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['account', 'year', 'month'], name='stripe_inte_account_84adf3_idx'), models.Index(fields=['year', 'month'], name='stripe_inte_year_ab52f6_idx')],
                'unique_together': {('account', 'year', 'month')},
            },
        ),
    ]
