# Generated by Django 4.2.24 on 2025-10-18 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Configuration Key",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Configuration value (can be JSON)",
                        verbose_name="Value",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of this setting",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this setting can be viewed by non-admin users",
                        verbose_name="Is Public",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="UserAppAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_code",
                    models.CharField(
                        help_text="Internal application identifier (e.g., expense_claims, leave_system)",
                        max_length=50,
                        verbose_name="Application Code",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("none", "No Access"),
                            ("employee", "Employee"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                        ],
                        default="employee",
                        help_text="User role within this application",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this access grant is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Granted At"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified At"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this access grant",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_app_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Granted By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_app_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_access_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User App Access",
                "verbose_name_plural": "User App Accesses",
                "ordering": ["user__email", "app_code"],
                "indexes": [
                    models.Index(
                        fields=["user", "app_code", "is_active"],
                        name="core_userap_user_id_f26e20_idx",
                    ),
                    models.Index(
                        fields=["app_code", "is_active"],
                        name="core_userap_app_cod_a8d2b9_idx",
                    ),
                ],
                "unique_together": {("user", "app_code")},
            },
        ),
        migrations.CreateModel(
            name="AppAccessAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_code",
                    models.CharField(max_length=50, verbose_name="Application Code"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("access_granted", "Access Granted"),
                            ("access_revoked", "Access Revoked"),
                            ("role_changed", "Role Changed"),
                            ("status_changed", "Status Changed"),
                            ("access_denied", "Access Denied"),
                            ("permission_checked", "Permission Checked"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Previous state before change",
                        verbose_name="Old Value",
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="New state after change",
                        verbose_name="New Value",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Details"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_access_modifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_access_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Access Audit Log",
                "verbose_name_plural": "App Access Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "app_code", "-created_at"],
                        name="core_appacc_user_id_cdb872_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_appacc_action_3fd0d1_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_appacc_created_41532c_idx"
                    ),
                ],
            },
        ),
    ]
