# Generated by Django 4.2.24 on 2025-10-18 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_code",
                    models.CharField(
                        db_index=True,
                        help_text="Internal app identifier (e.g., expense_claims)",
                        max_length=50,
                        unique=True,
                        verbose_name="Application Code",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        help_text="User-friendly app name",
                        max_length=100,
                        verbose_name="Application Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("developing", "Developing"),
                            ("prototype", "Prototype"),
                            ("uat", "UAT (User Acceptance Testing)"),
                            ("softlaunch", "Soft Launch"),
                            ("production", "Production"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="developing",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="0.1.0",
                        help_text="Current version number",
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True,
                        help_text="Port number if app runs on separate server",
                        null=True,
                        verbose_name="Port Number",
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        blank=True,
                        help_text="GitLab/GitHub repository URL",
                        verbose_name="Repository URL",
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Overall completion percentage (0-100)",
                        verbose_name="Completion %",
                    ),
                ),
                (
                    "functions_total",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of functions/features",
                        verbose_name="Total Functions",
                    ),
                ),
                (
                    "functions_complete",
                    models.IntegerField(
                        default=0,
                        help_text="Number of completed functions",
                        verbose_name="Complete Functions",
                    ),
                ),
                (
                    "started_at",
                    models.DateField(blank=True, null=True, verbose_name="Started At"),
                ),
                (
                    "prototype_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prototype Date"
                    ),
                ),
                (
                    "uat_date",
                    models.DateField(blank=True, null=True, verbose_name="UAT Date"),
                ),
                (
                    "softlaunch_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Soft Launch Date"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Production Date"
                    ),
                ),
                (
                    "target_launch_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Target Launch Date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Development notes, issues, blockers",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "known_issues",
                    models.TextField(
                        blank=True,
                        help_text="Known bugs and limitations",
                        verbose_name="Known Issues",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this app is actively maintained",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "developers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="developed_apps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Developers",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_apps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="App Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Status",
                "verbose_name_plural": "App Statuses",
                "ordering": ["priority", "app_name"],
            },
        ),
        migrations.CreateModel(
            name="AppStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="Old Status"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="New Status"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Reason for status change",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.appstatus",
                        verbose_name="Application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Status History",
                "verbose_name_plural": "App Status Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="Name of the function/feature",
                        max_length=200,
                        verbose_name="Function Name",
                    ),
                ),
                (
                    "function_code",
                    models.CharField(
                        help_text="Short identifier (e.g., expense_submit, leave_approve)",
                        max_length=50,
                        verbose_name="Function Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this function does",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("developing", "Developing"),
                            ("completed", "Completed"),
                            ("uat", "UAT"),
                            ("softlaunch", "Soft Launch"),
                            ("production", "Production"),
                            ("blocked", "Blocked"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_api",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an API endpoint",
                        verbose_name="Is API",
                    ),
                ),
                (
                    "is_ui",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this has UI components",
                        verbose_name="Is UI",
                    ),
                ),
                (
                    "has_tests",
                    models.BooleanField(
                        default=False,
                        help_text="Whether unit/integration tests exist",
                        verbose_name="Has Tests",
                    ),
                ),
                (
                    "has_documentation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user documentation exists",
                        verbose_name="Has Documentation",
                    ),
                ),
                (
                    "started_at",
                    models.DateField(blank=True, null=True, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Target Completion Date"
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Is Blocked"),
                ),
                (
                    "blocker_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why this function is blocked",
                        verbose_name="Blocker Reason",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functions",
                        to="core.appstatus",
                        verbose_name="Application",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_functions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by",
                        to="core.appfunction",
                        verbose_name="Depends On",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Function",
                "verbose_name_plural": "App Functions",
                "ordering": ["app", "priority", "function_name"],
                "unique_together": {("app", "function_code")},
            },
        ),
    ]
