# Generated by Django 4.2.24 on 2025-10-27 09:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("software", "Software Development"),
                            ("construction", "Construction"),
                            ("marketing", "Marketing Campaign"),
                            ("research", "Research Project"),
                            ("event", "Event Planning"),
                            ("consulting", "Consulting Project"),
                            ("design", "Design Project"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "default_duration_days",
                    models.IntegerField(help_text="Typical project duration"),
                ),
                (
                    "estimated_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated budget for projects created from this template",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Public templates visible to all users"
                    ),
                ),
                (
                    "use_count",
                    models.IntegerField(
                        default=0, help_text="Times this template was used"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("management", "Management"),
                            ("design", "Design"),
                            ("communication", "Communication"),
                            ("analysis", "Analysis"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Estimated hours to complete",
                        max_digits=8,
                    ),
                ),
                (
                    "assignee_role",
                    models.CharField(
                        choices=[
                            ("owner", "Project Owner"),
                            ("manager", "Project Manager"),
                            ("member", "Team Member"),
                            ("lead", "Team Lead"),
                        ],
                        default="member",
                        help_text="Role that should be assigned this task",
                        max_length=20,
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        default=0, help_text="Order in which tasks should be executed"
                    ),
                ),
                ("is_milestone", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_tasks",
                        to="project_management.projecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="TaskCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("labor", "Labor"),
                            ("material", "Material"),
                            ("equipment", "Equipment"),
                            ("other", "Other"),
                        ],
                        default="labor",
                        max_length=50,
                    ),
                ),
                (
                    "planned_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned/budgeted cost",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual cost incurred",
                        max_digits=10,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="project_management.task",
                    ),
                ),
            ],
            options={
                "ordering": ["task", "cost_type"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate for cost calculations",
                        max_digits=10,
                    ),
                ),
                (
                    "availability_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Percentage of time available for project work",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "working_hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard working hours per day",
                        max_digits=4,
                    ),
                ),
                ("start_date", models.DateField(help_text="When they joined the team")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When they leave (if applicable)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resources",
                        to="project_management.skill",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="created_from_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to create this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to="project_management.projecttemplate",
            ),
        ),
        migrations.CreateModel(
            name="TemplateDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("FS", "Finish-to-Start"),
                            ("SS", "Start-to-Start"),
                            ("FF", "Finish-to-Finish"),
                            ("SF", "Start-to-Finish"),
                        ],
                        default="FS",
                        max_length=2,
                    ),
                ),
                ("lag_days", models.IntegerField(default=0)),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_template_tasks",
                        to="project_management.templatetask",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_dependencies",
                        to="project_management.templatetask",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Template dependencies",
                "unique_together": {("task", "depends_on")},
            },
        ),
        migrations.CreateModel(
            name="ResourceAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Percentage of resource's time allocated to this task",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "assigned_hours",
                    models.DecimalField(
                        decimal_places=2, help_text="Total hours assigned", max_digits=8
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual hours spent",
                        max_digits=8,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="project_management.resource",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_assignments",
                        to="project_management.task",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["resource", "start_date", "end_date"],
                        name="project_man_resourc_daabcb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("labor", "Labor"),
                            ("materials", "Materials"),
                            ("equipment", "Equipment"),
                            ("subcontractor", "Subcontractor"),
                            ("travel", "Travel"),
                            ("software", "Software/Licenses"),
                            ("overhead", "Overhead"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["project", "date"],
                        name="project_man_project_70d0e6_idx",
                    ),
                    models.Index(
                        fields=["project", "category"],
                        name="project_man_project_69ba91_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EVMSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "budget_at_completion",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("planned_duration_days", models.IntegerField()),
                (
                    "planned_value",
                    models.DecimalField(
                        decimal_places=2, help_text="PV (BCWS)", max_digits=12
                    ),
                ),
                (
                    "earned_value",
                    models.DecimalField(
                        decimal_places=2, help_text="EV (BCWP)", max_digits=12
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="AC (ACWP)", max_digits=12
                    ),
                ),
                (
                    "cost_performance_index",
                    models.DecimalField(
                        decimal_places=2, help_text="CPI = EV/AC", max_digits=5
                    ),
                ),
                (
                    "schedule_performance_index",
                    models.DecimalField(
                        decimal_places=2, help_text="SPI = EV/PV", max_digits=5
                    ),
                ),
                (
                    "cost_variance",
                    models.DecimalField(
                        decimal_places=2, help_text="CV = EV - AC", max_digits=12
                    ),
                ),
                (
                    "schedule_variance",
                    models.DecimalField(
                        decimal_places=2, help_text="SV = EV - PV", max_digits=12
                    ),
                ),
                (
                    "estimate_at_completion",
                    models.DecimalField(
                        decimal_places=2, help_text="EAC", max_digits=12
                    ),
                ),
                (
                    "estimate_to_complete",
                    models.DecimalField(
                        decimal_places=2, help_text="ETC = EAC - AC", max_digits=12
                    ),
                ),
                (
                    "variance_at_completion",
                    models.DecimalField(
                        decimal_places=2, help_text="VAC = BAC - EAC", max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evm_snapshots",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["project", "-snapshot_date"],
                        name="project_man_project_1cd23f_idx",
                    )
                ],
                "unique_together": {("project", "snapshot_date")},
            },
        ),
    ]
