# Generated by Django 4.2.24 on 2025-10-27 09:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project_management",
            "0002_projecttemplate_skill_templatetask_taskcost_resource_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(default=django.utils.timezone.now)),
                ("tasks_total", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("tasks_in_progress", models.IntegerField(default=0)),
                ("tasks_overdue", models.IntegerField(default=0)),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("days_remaining", models.IntegerField(default=0)),
                (
                    "schedule_variance_days",
                    models.IntegerField(
                        default=0,
                        help_text="Positive = ahead of schedule, Negative = behind",
                    ),
                ),
                (
                    "budget_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Positive = under budget, Negative = over budget",
                        max_digits=12,
                    ),
                ),
                ("team_size", models.IntegerField(default=0)),
                (
                    "resource_utilization",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of team capacity used",
                        max_digits=5,
                    ),
                ),
                ("issues_open", models.IntegerField(default=0)),
                ("issues_resolved", models.IntegerField(default=0)),
                (
                    "velocity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tasks completed per week",
                        max_digits=6,
                    ),
                ),
                (
                    "health_score",
                    models.IntegerField(
                        default=100,
                        help_text="Overall project health score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_snapshots",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project metrics",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["project", "-snapshot_date"],
                        name="project_man_project_0668be_idx",
                    )
                ],
                "unique_together": {("project", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("project_status", "Project Status Overview"),
                            ("task_summary", "Task Summary"),
                            ("budget_tracker", "Budget Tracker"),
                            ("schedule_timeline", "Schedule Timeline"),
                            ("team_workload", "Team Workload"),
                            ("recent_activity", "Recent Activity"),
                            ("upcoming_deadlines", "Upcoming Deadlines"),
                            ("performance_metrics", "Performance Metrics"),
                            ("cost_breakdown", "Cost Breakdown"),
                            ("velocity_chart", "Velocity Chart"),
                            ("burndown_chart", "Burndown Chart"),
                            ("risk_alerts", "Risk Alerts"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1/4 width)"),
                            ("medium", "Medium (1/2 width)"),
                            ("large", "Large (Full width)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0, help_text="Display order on dashboard"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Widget-specific configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "position"],
                "unique_together": {("user", "widget_type")},
            },
        ),
    ]
