# Generated by Django 4.2.24 on 2025-10-28 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0004_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "current_page",
                    models.CharField(
                        blank=True,
                        help_text="Current page URL or identifier",
                        max_length=200,
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("session_start", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project the user is currently viewing",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_management.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task the user is currently viewing",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_management.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_online"],
                        name="project_man_user_id_17ce83_idx",
                    ),
                    models.Index(
                        fields=["project", "is_online"],
                        name="project_man_project_ee724c_idx",
                    ),
                    models.Index(
                        fields=["last_seen"], name="project_man_last_se_0f200c_idx"
                    ),
                ],
                "unique_together": {("user", "project")},
            },
        ),
    ]
