# Generated by Django 4.2.24 on 2025-10-28 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0005_userpresence"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique permission code (e.g., project.edit, task.delete)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("task", "Task"),
                            ("resource", "Resource"),
                            ("template", "Template"),
                            ("report", "Report"),
                            ("settings", "Settings"),
                            ("user", "User"),
                            ("role", "Role"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("assign", "Assign"),
                            ("approve", "Approve"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("share", "Share"),
                            ("comment", "Comment"),
                            ("manage", "Manage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system_permission",
                    models.BooleanField(
                        default=False, help_text="System permissions cannot be deleted"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="low",
                        help_text="Risk level for audit logging",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["resource_type", "action_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("project", "Project Level"),
                            ("task", "Task Level"),
                            ("resource", "Resource Level"),
                            ("global", "Global Level"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        help_text="Role hierarchy level (0=highest, 100=lowest)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="System roles cannot be deleted or modified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent role from which this role inherits permissions",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_roles",
                        to="project_management.customrole",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Template category (e.g., Development, Management, QA)",
                        max_length=100,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Public templates are available to all users",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional permissions beyond the base role",
                        related_name="templates",
                        to="project_management.custompermission",
                    ),
                ),
                (
                    "base_role",
                    models.ForeignKey(
                        help_text="The role this template is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="project_management.customrole",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("role_created", "Role Created"),
                            ("role_updated", "Role Updated"),
                            ("role_deleted", "Role Deleted"),
                            ("permission_created", "Permission Created"),
                            ("permission_updated", "Permission Updated"),
                            ("permission_deleted", "Permission Deleted"),
                            ("role_assigned", "Role Assigned to User"),
                            ("role_revoked", "Role Revoked from User"),
                            ("permission_granted", "Permission Granted"),
                            ("permission_denied", "Permission Denied"),
                            ("access_allowed", "Access Allowed"),
                            ("access_denied", "Access Denied"),
                            ("template_applied", "Template Applied"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of resource being accessed",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the resource being accessed",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what happened"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object containing before/after values",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("error", "Error"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if action failed"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audit_logs",
                        to="project_management.project",
                    ),
                ),
                (
                    "target_permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="project_management.custompermission",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="project_management.customrole",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User affected by the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="custompermission",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="permissions",
                to="project_management.customrole",
            ),
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Global role applies across all projects",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Role becomes active from this date",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Role expires after this date (null = no expiration)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this role assignment"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project-specific role assignment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="project_management.project",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resource-specific role assignment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="project_management.resource",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="project_management.customrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="project_man_user_id_671e30_idx",
                    ),
                    models.Index(
                        fields=["project", "is_active"],
                        name="project_man_project_96ad7c_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="project_man_valid_f_d8507b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userroleassignment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("project__isnull", False),
                    ("resource__isnull", False),
                    ("is_global", True),
                    _connector="OR",
                ),
                name="role_assignment_has_context",
            ),
        ),
        migrations.AddIndex(
            model_name="roletemplate",
            index=models.Index(
                fields=["category", "is_public"], name="project_man_categor_122c63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roletemplate",
            index=models.Index(
                fields=["-usage_count"], name="project_man_usage_c_dbe0f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["-timestamp"], name="project_man_timesta_8342de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="project_man_user_id_7fecc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["target_user", "-timestamp"],
                name="project_man_target__4985f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["action_type", "-timestamp"],
                name="project_man_action__13a7f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["project", "-timestamp"], name="project_man_project_26e820_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["status", "-timestamp"], name="project_man_status_145281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customrole",
            index=models.Index(
                fields=["role_type", "is_active"], name="project_man_role_ty_cdadf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customrole",
            index=models.Index(fields=["level"], name="project_man_level_2e06b6_idx"),
        ),
        migrations.AddIndex(
            model_name="custompermission",
            index=models.Index(
                fields=["code", "is_active"], name="project_man_code_0fd2c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custompermission",
            index=models.Index(
                fields=["resource_type", "action_type"],
                name="project_man_resourc_f77cb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="custompermission",
            index=models.Index(
                fields=["risk_level"], name="project_man_risk_le_26f189_idx"
            ),
        ),
    ]
