# Generated by Django 4.2.24 on 2025-10-28 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project_management",
            "0006_custompermission_customrole_roletemplate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("slack", "Slack"),
                            ("jira", "Jira"),
                            ("google_calendar", "Google Calendar"),
                            ("outlook_calendar", "Outlook Calendar"),
                            ("trello", "Trello"),
                            ("asana", "Asana"),
                            ("webhook", "Custom Webhook"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        help_text="OAuth Client ID or API Key",
                        max_length=500,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        blank=True,
                        help_text="OAuth Client Secret or API Secret (encrypted)",
                        max_length=500,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL for receiving events",
                        max_length=500,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for webhook signature validation",
                        max_length=200,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for API requests",
                        max_length=500,
                    ),
                ),
                ("oauth_authorize_url", models.URLField(blank=True, max_length=500)),
                ("oauth_token_url", models.URLField(blank=True, max_length=500)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional provider-specific configuration",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Global integration available to all projects",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, help_text="OAuth access token or API token"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(blank=True, help_text="OAuth refresh token"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Token expiration time", null=True
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External service ID (e.g., GitHub repo ID, Jira project key)",
                        max_length=500,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="External service URL", max_length=500
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic synchronization"
                    ),
                ),
                (
                    "sync_interval",
                    models.IntegerField(
                        default=300,
                        help_text="Sync interval in seconds (default: 5 minutes)",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful sync timestamp",
                        null=True,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("sync_error", models.TextField(blank=True)),
                (
                    "field_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field mappings between local and external service",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Integration-specific settings",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("configured_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="project_management.project",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_integrations",
                        to="project_management.integrationprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-configured_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of webhook event (e.g., push, pull_request, issue)",
                        max_length=100,
                    ),
                ),
                (
                    "event_action",
                    models.CharField(
                        blank=True,
                        help_text="Specific action (e.g., opened, closed, commented)",
                        max_length=100,
                    ),
                ),
                ("payload", models.JSONField(help_text="Complete webhook payload")),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="HTTP headers from webhook request",
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Processing result (created/updated objects)",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="project_management.projectintegration",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="project_management.integrationprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("sync", "Synchronization"),
                            ("webhook", "Webhook Received"),
                            ("export", "Data Export"),
                            ("import", "Data Import"),
                            ("api_call", "API Call"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional action details"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="API request data"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="API response data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Operation duration in milliseconds",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="project_management.projectintegration",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="project_management.integrationprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ExternalTaskMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="External task/issue ID", max_length=500
                    ),
                ),
                (
                    "external_key",
                    models.CharField(
                        blank=True,
                        help_text="External task key (e.g., PROJ-123)",
                        max_length=200,
                    ),
                ),
                ("external_url", models.URLField(max_length=500)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "external_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modified time on external service",
                        null=True,
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("both", "Bi-directional"),
                            ("import", "Import Only"),
                            ("export", "Export Only"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "field_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom field mappings for this task",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_task_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_mappings",
                        to="project_management.projectintegration",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_mappings",
                        to="project_management.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_synced_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projectintegration",
            index=models.Index(
                fields=["project", "is_active"], name="project_man_project_3688ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectintegration",
            index=models.Index(
                fields=["provider", "is_active"], name="project_man_provide_2ccf20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectintegration",
            index=models.Index(
                fields=["sync_status"], name="project_man_sync_st_2f52a4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectintegration",
            unique_together={("project", "provider")},
        ),
        migrations.AddIndex(
            model_name="integrationwebhook",
            index=models.Index(
                fields=["provider", "-received_at"],
                name="project_man_provide_fa7444_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationwebhook",
            index=models.Index(
                fields=["integration", "-received_at"],
                name="project_man_integra_3439e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationwebhook",
            index=models.Index(
                fields=["event_type", "-received_at"],
                name="project_man_event_t_087f8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationwebhook",
            index=models.Index(
                fields=["processed", "-received_at"],
                name="project_man_process_82624b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationprovider",
            index=models.Index(
                fields=["provider_type", "is_active"],
                name="project_man_provide_8659e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["integration", "-timestamp"],
                name="project_man_integra_d6631f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["provider", "-timestamp"], name="project_man_provide_5b2290_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["action_type", "-timestamp"],
                name="project_man_action__860437_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["status", "-timestamp"], name="project_man_status_6bf44a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externaltaskmapping",
            index=models.Index(
                fields=["task", "integration"], name="project_man_task_id_5b62d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externaltaskmapping",
            index=models.Index(
                fields=["integration", "sync_enabled"],
                name="project_man_integra_ac0e14_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externaltaskmapping",
            index=models.Index(
                fields=["external_id"], name="project_man_externa_007ce1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externaltaskmapping",
            unique_together={("integration", "external_id")},
        ),
    ]
