# Generated by Django 4.2.24 on 2025-10-28 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0007_integrationprovider_projectintegration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PWAInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("windows", "Windows"),
                            ("macos", "macOS"),
                            ("linux", "Linux"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=200)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "installed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                (
                    "push_token",
                    models.TextField(
                        blank=True, help_text="Device push notification token"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pwa_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_pwa_installation",
                "ordering": ["-installed_at"],
            },
        ),
        migrations.CreateModel(
            name="PWAAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("install", "App Installed"),
                            ("launch", "App Launched"),
                            ("page_view", "Page Viewed"),
                            ("offline", "Went Offline"),
                            ("online", "Came Online"),
                            ("sync", "Data Synchronized"),
                            ("notification", "Notification Received"),
                            ("action", "User Action"),
                            ("error", "Error Occurred"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                (
                    "connection_type",
                    models.CharField(
                        blank=True, help_text="wifi, 4g, offline, etc.", max_length=50
                    ),
                ),
                ("performance_metrics", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="project_management.pwainstallation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pwa_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_pwa_analytics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, unique=True)),
                (
                    "p256dh_key",
                    models.CharField(
                        help_text="Public key for encryption", max_length=200
                    ),
                ),
                (
                    "auth_key",
                    models.CharField(help_text="Authentication secret", max_length=200),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User notification preferences (types, frequency, etc.)",
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="project_management.pwainstallation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_push_subscription",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, help_text="ID of affected object", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(help_text="Operation data to be synchronized"),
                ),
                (
                    "original_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original data before change (for conflict resolution)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "conflict_resolution",
                    models.CharField(
                        blank=True,
                        help_text="Strategy used for conflict resolution",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority syncs first"
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_queue",
                        to="project_management.pwainstallation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_sync_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_offline_sync_queue",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("project", "Project Data"),
                            ("task", "Task Data"),
                            ("user", "User Data"),
                            ("resource", "Resource Data"),
                            ("static", "Static Assets"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cache_key", models.CharField(db_index=True, max_length=500)),
                ("data", models.JSONField(help_text="Cached data payload")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "size_bytes",
                    models.IntegerField(
                        default=0, help_text="Approximate size of cached data"
                    ),
                ),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cache_entries",
                        to="project_management.pwainstallation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_offline_cache",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pwainstallation",
            index=models.Index(
                fields=["user", "is_active"], name="project_pwa_user_id_1e170f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pwainstallation",
            index=models.Index(
                fields=["platform", "is_active"], name="project_pwa_platfor_21eaa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pwainstallation",
            index=models.Index(
                fields=["-last_active"], name="project_pwa_last_ac_7fbe95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pwaanalytics",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="project_pwa_event_t_78b974_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pwaanalytics",
            index=models.Index(
                fields=["user", "-timestamp"], name="project_pwa_user_id_d3f77a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pwaanalytics",
            index=models.Index(
                fields=["session_id", "-timestamp"],
                name="project_pwa_session_88fbda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="project_pus_user_id_b8135d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["is_active", "-subscribed_at"],
                name="project_pus_is_acti_366e1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinesyncqueue",
            index=models.Index(
                fields=["user", "status"], name="project_off_user_id_8dcc69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinesyncqueue",
            index=models.Index(
                fields=["status", "-priority", "created_at"],
                name="project_off_status_f9e93f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinesyncqueue",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="project_off_model_n_ff963e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinecache",
            index=models.Index(
                fields=["user", "cache_type"], name="project_off_user_id_5c246f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinecache",
            index=models.Index(
                fields=["expires_at"], name="project_off_expires_e668c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinecache",
            index=models.Index(
                fields=["-updated_at"], name="project_off_updated_2740d9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offlinecache",
            unique_together={("user", "cache_type", "cache_key")},
        ),
    ]
