# Generated by Django 4.2.24 on 2025-10-28 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project_management",
            "0008_pwainstallation_pwaanalytics_pushsubscription_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="Is this a reusable template?"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        help_text="Type of trigger that starts workflow", max_length=100
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(default=dict, help_text="Trigger configuration"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority workflows execute first"
                    ),
                ),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "retry_delay",
                    models.IntegerField(default=60, help_text="Retry delay in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project-specific workflow (null for global)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_workflow",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("task_created", "Task Created"),
                            ("task_updated", "Task Updated"),
                            ("task_status_changed", "Task Status Changed"),
                            ("task_assigned", "Task Assigned"),
                            ("task_due_soon", "Task Due Soon"),
                            ("task_overdue", "Task Overdue"),
                            ("project_created", "Project Created"),
                            ("project_updated", "Project Updated"),
                            ("schedule", "Scheduled Time"),
                            ("manual", "Manual Trigger"),
                            ("webhook", "Webhook Trigger"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions that must be met for trigger to fire",
                    ),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for scheduled triggers",
                        max_length=100,
                    ),
                ),
                ("schedule_timezone", models.CharField(default="UTC", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="project_management.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "project_workflow_trigger",
                "ordering": ["workflow", "trigger_type"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Execution context data (task, project, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Execution results and output",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("attempt", models.IntegerField(default=1)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "trigger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="project_management.workflowtrigger",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="project_management.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "project_workflow_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("send_notification", "Send Notification"),
                            ("update_task", "Update Task"),
                            ("create_task", "Create Task"),
                            ("assign_task", "Assign Task"),
                            ("change_status", "Change Status"),
                            ("add_comment", "Add Comment"),
                            ("webhook", "Call Webhook"),
                            ("delay", "Delay"),
                            ("conditional", "Conditional Branch"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Execution order (lower executes first)"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Action-specific parameters"
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Condition for executing this action",
                    ),
                ),
                (
                    "continue_on_error",
                    models.BooleanField(
                        default=False,
                        help_text="Continue workflow if this action fails",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="project_management.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "project_workflow_action",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("auto_assign", "Auto-assign tasks"),
                            ("status_transition", "Auto-transition status"),
                            ("send_reminder", "Send reminders"),
                            ("escalate", "Escalate overdue tasks"),
                            ("archive", "Auto-archive completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(default=dict, help_text="When to apply rule"),
                ),
                ("actions", models.JSONField(default=dict, help_text="What to do")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "run_schedule",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for scheduled rules",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_automation_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowtrigger",
            index=models.Index(
                fields=["workflow", "is_active"], name="project_wor_workflo_41afb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtrigger",
            index=models.Index(
                fields=["trigger_type"], name="project_wor_trigger_a5ca25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "-created_at"],
                name="project_wor_workflo_7b7f66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "-created_at"], name="project_wor_status_bfa543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["triggered_by", "-created_at"],
                name="project_wor_trigger_68aadb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["workflow", "order"], name="project_wor_workflo_c5ee33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowaction",
            index=models.Index(
                fields=["action_type"], name="project_wor_action__d52b99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["status", "-priority"], name="project_wor_status_cde97e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["project", "status"], name="project_wor_project_32448d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["trigger_type"], name="project_wor_trigger_7ca329_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["-last_executed"], name="project_wor_last_ex_b78b32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["project", "is_active"], name="project_aut_project_0aac03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["rule_type"], name="project_aut_rule_ty_56c480_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["-last_run"], name="project_aut_last_ru_60c95a_idx"
            ),
        ),
    ]
