# Generated by Django 4.2.16 on 2025-11-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_workflow_workflowtrigger_workflowexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title_cn',
            field=models.CharField(blank=True, max_length=300, verbose_name='Chinese Title'),
        ),
    ]
