# Generated by Django 4.2.16 on 2025-11-12 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0010_task_title_cn'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='definition_of_done',
            field=models.TextField(blank=True, help_text='Acceptance criteria and completion requirements', verbose_name='Definition of Done'),
        ),
        migrations.AddField(
            model_name='task',
            name='process_owner',
            field=models.ForeignKey(blank=True, help_text='Single accountable owner for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Process Owner'),
        ),
    ]
