# Generated by Django 4.2.16 on 2025-12-03 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0011_task_definition_of_done_task_process_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process_members',
            field=models.ManyToManyField(blank=True, help_text='Team members working on this task under the process owner', related_name='process_member_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Process Members'),
        ),
    ]
