# Generated by Django 4.2.16 on 2025-12-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/photos/'),
        ),
    ]
