# Generated by Django 4.2.16 on 2025-12-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF, Word, Excel or other document files', null=True, upload_to='assets/documents/'),
        ),
    ]
