# Generated by Django 4.2.16 on 2025-12-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_primary_user_alter_asset_responsible_person'),
        ('assets', '0003_asset_document'),
    ]

    operations = [
    ]
