# Generated by Django 4.2.16 on 2026-01-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Internal identifier (e.g., expense_claims, leave_management)",
                        max_length=50,
                        unique=True,
                        verbose_name="App Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name shown in dashboard",
                        max_length=100,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the application",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-cube",
                        help_text="Font Awesome icon class (e.g., fas fa-receipt)",
                        max_length=50,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color for app card/button",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("finance", "Finance"),
                            ("hr", "Human Resources"),
                            ("operations", "Operations"),
                            ("sales", "Sales & CRM"),
                            ("admin", "Administration"),
                            ("system", "System"),
                        ],
                        default="operations",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=100,
                        help_text="Order in dashboard (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        help_text="Internal URL path (e.g., /expense-claims/)",
                        max_length=200,
                        verbose_name="URL Path",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL if app runs on separate server",
                        verbose_name="External URL",
                    ),
                ),
                (
                    "internal_port",
                    models.IntegerField(
                        blank=True,
                        help_text="Port number if app runs separately",
                        null=True,
                        verbose_name="Internal Port",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("developing", "Developing"),
                            ("prototype", "Prototype"),
                            ("uat", "UAT"),
                            ("softlaunch", "Soft Launch"),
                            ("production", "Production"),
                            ("maintenance", "Maintenance"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="developing",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Global enable/disable for all users",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "requires_permission",
                    models.BooleanField(
                        default=True,
                        help_text="Whether users need explicit access to use this app",
                        verbose_name="Requires Permission",
                    ),
                ),
                (
                    "permission_key",
                    models.CharField(
                        blank=True,
                        help_text="Key used in SSO token permissions (e.g., expense_system)",
                        max_length=50,
                        verbose_name="Permission Key",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Show maintenance message instead of app",
                        verbose_name="Maintenance Mode",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="This application is currently under maintenance.",
                        verbose_name="Maintenance Message",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="Version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Configuration",
                "verbose_name_plural": "Application Configurations",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Department Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Department Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AppAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("access_granted", "Access Granted"),
                            ("access_revoked", "Access Revoked"),
                            ("access_modified", "Access Modified"),
                            ("app_accessed", "App Accessed"),
                            ("access_denied", "Access Denied"),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Details"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "app",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="app_registry.applicationconfig",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_app_access_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App Access Log",
                "verbose_name_plural": "App Access Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAppAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("none", "No Access"),
                            ("view", "View Only"),
                            ("edit", "View & Edit"),
                            ("admin", "Full Admin"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Access Level",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Is Enabled"),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_access",
                        to="app_registry.applicationconfig",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_user_app_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_registry_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User App Access",
                "verbose_name_plural": "User App Accesses",
                "ordering": ["user__email", "app__name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_enabled"],
                        name="app_registr_user_id_e81d56_idx",
                    ),
                    models.Index(
                        fields=["app", "access_level"],
                        name="app_registr_app_id_da053f_idx",
                    ),
                ],
                "unique_together": {("user", "app")},
            },
        ),
        migrations.CreateModel(
            name="DepartmentAppAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this department can access this app",
                        verbose_name="Is Enabled",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_access",
                        to="app_registry.applicationconfig",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_access",
                        to="app_registry.department",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_department_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department App Access",
                "verbose_name_plural": "Department App Accesses",
                "ordering": ["department__name", "app__name"],
                "unique_together": {("department", "app")},
            },
        ),
        migrations.AddIndex(
            model_name="applicationconfig",
            index=models.Index(
                fields=["code", "is_active"], name="app_registr_code_b7527d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationconfig",
            index=models.Index(
                fields=["status", "is_active"], name="app_registr_status_330e3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationconfig",
            index=models.Index(
                fields=["category", "display_order"],
                name="app_registr_categor_024761_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appaccesslog",
            index=models.Index(
                fields=["user", "-created_at"], name="app_registr_user_id_dec239_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appaccesslog",
            index=models.Index(
                fields=["app", "-created_at"], name="app_registr_app_id_f90bbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appaccesslog",
            index=models.Index(
                fields=["action", "-created_at"], name="app_registr_action_7267a3_idx"
            ),
        ),
    ]
