# Generated by Django 4.2.23 on 2025-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave_management", "0002_pendingregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="region",
            field=models.CharField(
                choices=[("HK", "Hong Kong"), ("CN", "China")],
                default="HK",
                max_length=2,
            ),
        ),
    ]
