# Generated by Django 4.2.16 on 2025-11-27 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('assets', '0002_asset_primary_user_alter_asset_responsible_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expected_arrival_date', models.DateTimeField()),
                ('actual_departure_date', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bulk_movements', to=settings.AUTH_USER_MODEL)),
                ('assets', models.ManyToManyField(related_name='bulk_movements', to='assets.asset')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_outgoing_movements', to='locations.location')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_bulk_movements', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_incoming_movements', to='locations.location')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_number'], name='movements_b_trackin_e65fc8_idx'), models.Index(fields=['status'], name='movements_b_status_b03c79_idx'), models.Index(fields=['expected_arrival_date'], name='movements_b_expecte_4bfc12_idx')],
            },
        ),
    ]
