# Generated by Django 4.2.16 on 2025-10-28 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_dashboard_widgets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
