# Generated by Django 4.2.16 on 2025-09-29 03:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Company email address used for login', max_length=254, unique=True, verbose_name='Email Address')),
                ('employee_id', models.CharField(help_text='Unique employee identification number', max_length=20, unique=True, verbose_name='Employee ID')),
                ('region', models.CharField(choices=[('HK', 'Hong Kong'), ('CN', 'China'), ('GLOBAL', 'Global')], default='HK', help_text='Primary work region', max_length=10, verbose_name='Region')),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('IT', 'Information Technology'), ('OPERATIONS', 'Operations'), ('SALES', 'Sales & Marketing'), ('MANAGEMENT', 'Management'), ('ADMIN', 'Administration')], help_text='Department/Division', max_length=20, verbose_name='Department')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='Phone Number')),
                ('apps_access', models.JSONField(blank=True, default=list, help_text='List of applications this user can access', verbose_name='Allowed Applications')),
                ('sso_token', models.UUIDField(default=uuid.uuid4, help_text='Single Sign-On token for cross-app authentication', unique=True, verbose_name='SSO Token')),
                ('last_sso_login', models.DateTimeField(blank=True, help_text='Last time user logged in via SSO', null=True, verbose_name='Last SSO Login')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'ordering': ['department', 'last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name of the application', max_length=50, unique=True, verbose_name='Application Name')),
                ('display_name', models.CharField(help_text='User-friendly name shown in interface', max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Brief description of the application', verbose_name='Description')),
                ('url', models.URLField(help_text='Base URL for the application', verbose_name='Application URL')),
                ('icon', models.CharField(default='fas fa-app', help_text='CSS class for application icon', max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for application theme', max_length=7, verbose_name='Theme Color')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this application is available for use', verbose_name='Is Active')),
                ('requires_sso', models.BooleanField(default=True, help_text='Whether this application uses SSO authentication', verbose_name='Requires SSO')),
                ('sso_secret', models.CharField(blank=True, help_text='Secret key for SSO token validation', max_length=255, verbose_name='SSO Secret')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display in the app grid', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Configuration',
                'verbose_name_plural': 'Application Configurations',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Session Key')),
                ('app_name', models.CharField(help_text='Name of the application for this session', max_length=50, verbose_name='Application')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('expires_at', models.DateTimeField(help_text='When this session expires', verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
