# Generated by Django 4.2.24 on 2025-10-18 06:31

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="companyuser",
            managers=[
                ("objects", authentication.models.CompanyUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_user_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
