# Generated by Django 4.2.16 on 2025-10-28 04:25

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyuser',
            managers=[
                ('objects', authentication.models.CompanyUserManager()),
            ],
        ),
    ]
