# Generated by Django 4.2.16 on 2025-10-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_companyuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationconfig',
            options={'ordering': ['display_name'], 'verbose_name': 'Application Configuration', 'verbose_name_plural': 'Application Configurations'},
        ),
        migrations.AddField(
            model_name='companyuser',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='User must change password on next login', verbose_name='Password Change Required'),
        ),
    ]
