# Generated by Django 4.2.24 on 2025-10-20 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_companyuser_managers_alter_usersession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When user was approved",
                null=True,
                verbose_name="Approved At",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether user registration has been approved by superadmin",
                verbose_name="Is Approved",
            ),
        ),
    ]
