# Generated by Django 4.2.16 on 2025-11-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_applicationconfig_options_and_more'),
        ('authentication', '0003_companyuser_approved_at_companyuser_approved_by_and_more'),
    ]

    operations = [
    ]
