# Generated by Django 4.2.16 on 2025-11-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_is_approved_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='allow_superuser_access',
            field=models.BooleanField(default=True, help_text='Allow superusers to bypass maintenance mode', verbose_name='Allow Superuser Access'),
        ),
        migrations.AddField(
            model_name='applicationconfig',
            name='is_maintenance',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode to show a message to users', verbose_name='Maintenance Mode'),
        ),
        migrations.AddField(
            model_name='applicationconfig',
            name='maintenance_message',
            field=models.TextField(blank=True, help_text='Message to display when in maintenance mode (supports HTML)', verbose_name='Maintenance Message'),
        ),
        migrations.AddField(
            model_name='applicationconfig',
            name='maintenance_message_cn',
            field=models.TextField(blank=True, help_text='Chinese version of maintenance message', verbose_name='Maintenance Message (Chinese)'),
        ),
    ]
