# Generated by Django 4.2.16 on 2025-11-18 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_id', models.CharField(default=uuid.uuid4, help_text='Unique identifier for QR code', max_length=50, unique=True, verbose_name='Unique ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('participant_class', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('student', 'Student'), ('staff', 'Staff'), ('guest', 'Guest')], default='regular', max_length=20, verbose_name='Participant Class')),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR code image', upload_to='qr_codes/', verbose_name='QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked SSO account (optional for external participants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Participant',
                'verbose_name_plural': 'QR Participants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField(default=100, help_text='Maximum number of people allowed in venue', verbose_name='Maximum Capacity')),
                ('warning_threshold', models.IntegerField(default=90, help_text='Show warning when capacity reaches this percentage', verbose_name='Warning Threshold (%)')),
                ('enable_capacity_limit', models.BooleanField(default=True, help_text='Block check-ins when venue is at maximum capacity', verbose_name='Enable Capacity Limit')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venue Settings',
                'verbose_name_plural': 'Venue Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('scan_in', 'Scan Check-In'), ('scan_out', 'Scan Check-Out'), ('override', 'Duplicate Override'), ('participant_add', 'Participant Added'), ('participant_edit', 'Participant Edited'), ('participant_delete', 'Participant Deleted'), ('settings_change', 'Settings Changed')], max_length=50, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qr_attendance.participant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Audit Log',
                'verbose_name_plural': 'QR Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField(verbose_name='Check-In Time')),
                ('time_out', models.DateTimeField(blank=True, null=True, verbose_name='Check-Out Time')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Calculated when checked out', null=True, verbose_name='Duration (Minutes)')),
                ('checked_in', models.BooleanField(default=True, help_text='True if participant is currently inside venue', verbose_name='Currently Checked In')),
                ('override_reason', models.TextField(blank=True, help_text='Reason for duplicate entry override', verbose_name='Override Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_records', to='qr_attendance.participant')),
                ('scanned_by', models.ForeignKey(blank=True, help_text='Operator who scanned this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_qr_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Attendance Record',
                'verbose_name_plural': 'QR Attendance Records',
                'ordering': ['-time_in'],
                'indexes': [models.Index(fields=['participant', '-time_in'], name='qr_attendan_partici_95543f_idx'), models.Index(fields=['checked_in'], name='qr_attendan_checked_fa3329_idx')],
            },
        ),
    ]
