# Generated by Django 4.2.16 on 2025-11-18 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the venue/location', max_length=100, verbose_name='Venue Name')),
                ('code', models.CharField(help_text='Short code for the venue (e.g., HALL_A, ROOM_101)', max_length=50, unique=True, verbose_name='Venue Code')),
                ('location', models.CharField(blank=True, help_text='Physical address or location description', max_length=255, verbose_name='Location/Address')),
                ('max_capacity', models.IntegerField(default=100, help_text='Maximum number of people allowed in this venue', verbose_name='Maximum Capacity')),
                ('warning_threshold', models.IntegerField(default=90, help_text='Show warning when capacity reaches this percentage', verbose_name='Warning Threshold (%)')),
                ('enable_capacity_limit', models.BooleanField(default=True, help_text='Block check-ins when venue is at maximum capacity', verbose_name='Enable Capacity Limit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this venue is currently active', verbose_name='Is Active')),
                ('description', models.TextField(blank=True, help_text='Additional venue information', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='venuesettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='VenueSettings',
        ),
        migrations.AlterField(
            model_name='qrattendancerecord',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_records', to='qr_attendance.participant'),
        ),
        migrations.AddField(
            model_name='qrattendancerecord',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Venue/Location where check-in occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='qr_attendance.venue'),
        ),
        migrations.AddIndex(
            model_name='qrattendancerecord',
            index=models.Index(fields=['venue', 'checked_in'], name='qr_attendan_venue_i_8e25eb_idx'),
        ),
    ]
