# Generated by Django 4.2.16 on 2026-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_centre',
            field=models.CharField(blank=True, choices=[('', 'Select Centre'), ('hk', 'Hong Kong'), ('cn', 'China Mainland'), ('sg', 'Singapore'), ('tw', 'Taiwan'), ('my', 'Malaysia'), ('th', 'Thailand'), ('vn', 'Vietnam'), ('id', 'Indonesia'), ('ph', 'Philippines'), ('jp', 'Japan'), ('kr', 'Korea'), ('au', 'Australia'), ('nz', 'New Zealand'), ('uk', 'United Kingdom'), ('us', 'United States'), ('eu', 'Europe'), ('other', 'Other')], help_text="Customer's assigned service centre", max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_subscribed',
            field=models.CharField(blank=True, choices=[('', 'Select Service'), ('blender_studio', 'Blender Studio'), ('origin_cg', 'Origin CG'), ('krystal_institute', 'Krystal Institute'), ('krystal_technology', 'Krystal Technology'), ('cgge', 'CGGE'), ('online_course', 'Online Course'), ('workshop', 'Workshop'), ('mentorship', 'Mentorship Program'), ('corporate_training', 'Corporate Training'), ('consulting', 'Consulting'), ('other', 'Other')], help_text='Primary service the customer subscribed to', max_length=30),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_centre'], name='crm_custome_custome_b263f1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['service_subscribed'], name='crm_custome_service_ae5564_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_centre', 'service_subscribed'], name='crm_custome_custome_804c3f_idx'),
        ),
    ]
