# Generated by Django 4.2.16 on 2025-10-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_claims', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='expense_cla_code_3e6070_idx',
            old_name='claims_comp_code_aa8a54_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='expense_cla_is_acti_ae73d7_idx',
            old_name='claims_comp_is_acti_249c79_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='expense_cla_code_d64cd2_idx',
            old_name='claims_expe_code_cf75d6_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='expense_cla_is_acti_5b0eec_idx',
            old_name='claims_expe_is_acti_e0ecfc_idx',
        ),
    ]
