# Generated by Django 4.2.16 on 2025-12-15 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_claims', '0002_rename_claims_comp_code_aa8a54_idx_expense_cla_code_3e6070_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='claims_comp_code_aa8a54_idx',
            old_name='expense_cla_code_3e6070_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='claims_comp_is_acti_249c79_idx',
            old_name='expense_cla_is_acti_ae73d7_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='claims_expe_code_cf75d6_idx',
            old_name='expense_cla_code_d64cd2_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='claims_expe_is_acti_e0ecfc_idx',
            old_name='expense_cla_is_acti_5b0eec_idx',
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='claim_for',
            field=models.ForeignKey(blank=True, help_text='The user for whom this expense is being claimed (if different from claimant)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims_for_user', to=settings.AUTH_USER_MODEL, verbose_name='Claim For'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='claimant',
            field=models.ForeignKey(help_text='The user who is submitting this claim (applicant)', on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to=settings.AUTH_USER_MODEL, verbose_name='Claimant'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Amount'),
        ),
        migrations.AlterModelTable(
            name='claimcomment',
            table='claims_claimcomment',
        ),
        migrations.AlterModelTable(
            name='claimstatushistory',
            table='claims_claimstatushistory',
        ),
        migrations.AlterModelTable(
            name='company',
            table='claims_company',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='claims_currency',
        ),
        migrations.AlterModelTable(
            name='exchangerate',
            table='claims_exchangerate',
        ),
        migrations.AlterModelTable(
            name='expensecategory',
            table='claims_expensecategory',
        ),
        migrations.AlterModelTable(
            name='expenseclaim',
            table='claims_expenseclaim',
        ),
        migrations.AlterModelTable(
            name='expenseitem',
            table='claims_expenseitem',
        ),
    ]
