# Generated by Django 4.2.16 on 2025-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_claims', '0003_add_claim_for_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseclaim',
            options={'ordering': ['display_order', '-created_at'], 'permissions': [('can_approve_claims', 'Can approve expense claims'), ('can_view_all_claims', 'Can view all expense claims')], 'verbose_name': 'Expense Claim', 'verbose_name_plural': 'Expense Claims'},
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Custom sort order for dashboard display', verbose_name='Display Order'),
        ),
    ]
