# Generated by Django 4.2.24 on 2025-10-27 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_number",
                    models.CharField(
                        help_text="Unique event identifier (e.g., DECT-AI-20250222)",
                        max_length=50,
                        unique=True,
                        verbose_name="Event Number",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("installation", "Hardware Installation & Configuration"),
                            ("training", "On-site Training"),
                            ("maintenance", "Maintenance Service"),
                            ("sales_visit", "Sales Visit"),
                            ("consultation", "Technical Consultation"),
                        ],
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "customer_company",
                    models.CharField(max_length=200, verbose_name="Customer Company"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="Contact Person"),
                ),
                (
                    "contact_position",
                    models.CharField(max_length=100, verbose_name="Position"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=50, verbose_name="Phone"),
                ),
                (
                    "contact_wechat",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WeChat ID"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                ("delivery_address", models.TextField(verbose_name="Delivery Address")),
                (
                    "installation_address",
                    models.TextField(
                        blank=True,
                        help_text="Leave blank if same as delivery address",
                        verbose_name="Installation/Maintenance Address",
                    ),
                ),
                (
                    "training_address",
                    models.TextField(
                        blank=True,
                        help_text="Leave blank if same as delivery address",
                        verbose_name="Training Address",
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="Planned Start Date"),
                ),
                ("planned_end_date", models.DateField(verbose_name="Planned End Date")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Start Date"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual End Date"
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.IntegerField(verbose_name="Estimated Duration (Days)"),
                ),
                (
                    "estimated_total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Estimated Total Cost",
                    ),
                ),
                (
                    "actual_total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Actual Total Cost",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RMB", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "assigned_staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned Staff",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "sales_responsible",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsible Sales Personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event/Visit",
                "verbose_name_plural": "Events/Visits",
                "ordering": ["-planned_start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_management_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        verbose_name="Time Management",
                    ),
                ),
                (
                    "technical_quality_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        verbose_name="Technical Quality",
                    ),
                ),
                (
                    "customer_satisfaction_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        verbose_name="Customer Satisfaction",
                    ),
                ),
                (
                    "cost_efficiency_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        verbose_name="Cost Efficiency",
                    ),
                ),
                ("what_went_well", models.TextField(verbose_name="What Went Well")),
                (
                    "areas_for_improvement",
                    models.TextField(verbose_name="Areas for Improvement"),
                ),
                ("lessons_learned", models.TextField(verbose_name="Lessons Learned")),
                ("recommendations", models.TextField(verbose_name="Recommendations")),
                (
                    "customer_feedback",
                    models.TextField(blank=True, verbose_name="Customer Feedback"),
                ),
                (
                    "customer_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_signatures/%Y/%m/",
                        verbose_name="Customer Signature",
                    ),
                ),
                (
                    "customer_signed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Customer Signed Date"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(auto_now_add=True, verbose_name="Review Date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Review",
                "verbose_name_plural": "Event Reviews",
            },
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("code_conduct", "Code of Conduct"),
                            ("safety", "Safety Protocol"),
                            ("customer_service", "Customer Service Ethics"),
                            ("checklist", "Pre-Departure Checklist"),
                            ("equipment", "Equipment Checkout"),
                            ("custom", "Custom Reminder"),
                        ],
                        max_length=20,
                        verbose_name="Reminder Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "send_datetime",
                    models.DateTimeField(verbose_name="Send Date & Time"),
                ),
                ("sent", models.BooleanField(default=False, verbose_name="Sent")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="event_reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipients",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Reminder",
                "verbose_name_plural": "Event Reminders",
                "ordering": ["send_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware/Equipment"),
                            ("software", "Software/Tools"),
                            ("documentation", "Documentation"),
                            ("travel", "Travel Arrangements"),
                            ("customer", "Customer Requirements"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsible Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Prerequisite",
                "verbose_name_plural": "Event Prerequisites",
                "ordering": ["due_date", "status"],
            },
        ),
        migrations.CreateModel(
            name="EventEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=200, verbose_name="Equipment Name"),
                ),
                (
                    "equipment_serial",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Serial Number"
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Quantity")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked_out", "Checked Out"),
                            ("in_use", "In Use"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                        ],
                        default="checked_out",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "checked_out_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Checked Out Date"
                    ),
                ),
                (
                    "returned_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Returned Date"
                    ),
                ),
                (
                    "condition_notes",
                    models.TextField(blank=True, verbose_name="Condition Notes"),
                ),
                (
                    "damage_report",
                    models.TextField(blank=True, verbose_name="Damage Report"),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_checked_out",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Checked Out By",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_returned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Returned By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Equipment",
                "verbose_name_plural": "Event Equipment",
                "ordering": ["-checked_out_date"],
            },
        ),
        migrations.CreateModel(
            name="EventCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            (
                                "personnel_installation",
                                "Personnel - Installation (¥1,500/day)",
                            ),
                            (
                                "personnel_configuration",
                                "Personnel - Configuration (¥4,000/day)",
                            ),
                            ("personnel_training", "Personnel - Training (¥3,000/day)"),
                            (
                                "personnel_maintenance",
                                "Personnel - Maintenance (¥4,000/day)",
                            ),
                            ("accommodation", "Accommodation"),
                            ("transport", "Transportation"),
                            ("allowance", "Travel Allowance"),
                            ("hardware", "Hardware/Materials"),
                            ("other", "Other Expenses"),
                        ],
                        max_length=30,
                        verbose_name="Cost Type",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate per day for personnel costs",
                        max_digits=10,
                        null=True,
                        verbose_name="Daily Rate",
                    ),
                ),
                (
                    "days_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Days"
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Estimated Amount"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Actual Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RMB", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "receipt_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="event_receipts/%Y/%m/",
                        verbose_name="Receipt",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Staff Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Cost",
                "verbose_name_plural": "Event Costs",
                "ordering": ["cost_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventWorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(verbose_name="Log Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                ("work_description", models.TextField(verbose_name="Work Description")),
                ("tasks_completed", models.TextField(verbose_name="Tasks Completed")),
                (
                    "issues_encountered",
                    models.TextField(blank=True, verbose_name="Issues Encountered"),
                ),
                (
                    "notes_recommendations",
                    models.TextField(
                        blank=True, verbose_name="Notes and Recommendations"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of photo file paths",
                        verbose_name="Photos",
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of document file paths",
                        verbose_name="Documents",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_logs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "staff_members",
                    models.ManyToManyField(
                        related_name="work_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Staff Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Work Log",
                "verbose_name_plural": "Event Work Logs",
                "ordering": ["-log_date", "-start_time"],
                "unique_together": {("event", "log_date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="EventApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_role",
                    models.CharField(
                        choices=[
                            ("financial", "Financial Supervisor"),
                            ("technical", "Technical Supervisor"),
                            ("procurement", "Procurement Personnel"),
                            ("business", "Business Supervisor"),
                        ],
                        max_length=20,
                        verbose_name="Approval Role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Approval",
                "verbose_name_plural": "Event Approvals",
                "ordering": ["created_at"],
                "unique_together": {("event", "approval_role")},
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_number"], name="event_manag_event_n_f66621_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="event_manag_status_6e606b_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["planned_start_date"], name="event_manag_planned_5092e5_idx"
            ),
        ),
    ]
