# Generated by Django 4.2.24 on 2025-10-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreminder",
            name="email_error",
            field=models.TextField(blank=True, verbose_name="Email Error"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="Email Sent"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="send_email",
            field=models.BooleanField(default=True, verbose_name="Send Email"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="send_sms",
            field=models.BooleanField(default=False, verbose_name="Send SMS"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="send_wechat",
            field=models.BooleanField(default=False, verbose_name="Send WeChat"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="sms_error",
            field=models.TextField(blank=True, verbose_name="SMS Error"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="sms_sent",
            field=models.BooleanField(default=False, verbose_name="SMS Sent"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="wechat_error",
            field=models.TextField(blank=True, verbose_name="WeChat Error"),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="wechat_sent",
            field=models.BooleanField(default=False, verbose_name="WeChat Sent"),
        ),
    ]
