# Generated by Django 4.2.24 on 2025-10-27 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "event_management",
            "0002_eventreminder_email_error_eventreminder_email_sent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentDamageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Damage"),
                            ("water", "Water Damage"),
                            ("electrical", "Electrical Failure"),
                            ("wear_tear", "Normal Wear and Tear"),
                            ("missing", "Missing Components"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Damage Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor - Cosmetic damage only"),
                            ("moderate", "Moderate - Affects functionality"),
                            ("severe", "Severe - Equipment unusable"),
                            ("total_loss", "Total Loss - Beyond repair"),
                        ],
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                ("description", models.TextField(verbose_name="Damage Description")),
                (
                    "discovered_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Discovered Date"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where was the damage discovered?",
                        max_length=200,
                        verbose_name="Location",
                    ),
                ),
                (
                    "suspected_cause",
                    models.TextField(
                        blank=True,
                        help_text="What might have caused this damage?",
                        verbose_name="Suspected Cause",
                    ),
                ),
                (
                    "preventable",
                    models.BooleanField(
                        default=False,
                        help_text="Could this damage have been prevented?",
                        verbose_name="Preventable",
                    ),
                ),
                (
                    "prevention_notes",
                    models.TextField(
                        blank=True,
                        help_text="How could this have been prevented?",
                        verbose_name="Prevention Notes",
                    ),
                ),
                (
                    "estimated_repair_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Estimated Repair Cost",
                    ),
                ),
                (
                    "actual_repair_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Actual Repair Cost",
                    ),
                ),
                (
                    "replacement_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Replacement Cost",
                    ),
                ),
                (
                    "repair_required",
                    models.BooleanField(default=True, verbose_name="Repair Required"),
                ),
                (
                    "repair_completed",
                    models.BooleanField(default=False, verbose_name="Repair Completed"),
                ),
                (
                    "repair_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Repair Completion Date"
                    ),
                ),
                (
                    "responsible_party",
                    models.CharField(
                        blank=True,
                        help_text="Who is responsible for the damage?",
                        max_length=200,
                        verbose_name="Responsible Party",
                    ),
                ),
                (
                    "insurance_claim_filed",
                    models.BooleanField(
                        default=False, verbose_name="Insurance Claim Filed"
                    ),
                ),
                (
                    "insurance_claim_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Insurance Claim Number",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Internal Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discovered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damage_reports_discovered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Discovered By",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_reports",
                        to="event_management.eventequipment",
                        verbose_name="Equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Damage Report",
                "verbose_name_plural": "Equipment Damage Reports",
                "ordering": ["-discovered_date"],
            },
        ),
        migrations.CreateModel(
            name="DamagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Photo of the damage",
                        upload_to="damage_photos/%Y/%m/%d/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of what this photo shows",
                        max_length=200,
                        verbose_name="Caption",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "damage_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="event_management.equipmentdamagereport",
                        verbose_name="Damage Report",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damage_photos_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Damage Photo",
                "verbose_name_plural": "Damage Photos",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Feedback Token",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Customer Name"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Customer Email"),
                ),
                (
                    "customer_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Position"
                    ),
                ),
                (
                    "service_quality_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Very Dissatisfied"),
                            (2, "2 - Dissatisfied"),
                            (3, "3 - Neutral"),
                            (4, "4 - Satisfied"),
                            (5, "5 - Very Satisfied"),
                        ],
                        help_text="How would you rate the overall service quality?",
                        verbose_name="Service Quality",
                    ),
                ),
                (
                    "staff_professionalism_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Very Dissatisfied"),
                            (2, "2 - Dissatisfied"),
                            (3, "3 - Neutral"),
                            (4, "4 - Satisfied"),
                            (5, "5 - Very Satisfied"),
                        ],
                        help_text="How professional were our staff members?",
                        verbose_name="Staff Professionalism",
                    ),
                ),
                (
                    "timeliness_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Very Dissatisfied"),
                            (2, "2 - Dissatisfied"),
                            (3, "3 - Neutral"),
                            (4, "4 - Satisfied"),
                            (5, "5 - Very Satisfied"),
                        ],
                        help_text="How satisfied were you with our punctuality and time management?",
                        verbose_name="Timeliness",
                    ),
                ),
                (
                    "technical_expertise_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Very Dissatisfied"),
                            (2, "2 - Dissatisfied"),
                            (3, "3 - Neutral"),
                            (4, "4 - Satisfied"),
                            (5, "5 - Very Satisfied"),
                        ],
                        help_text="How would you rate our technical knowledge and expertise?",
                        verbose_name="Technical Expertise",
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Very Dissatisfied"),
                            (2, "2 - Dissatisfied"),
                            (3, "3 - Neutral"),
                            (4, "4 - Satisfied"),
                            (5, "5 - Very Satisfied"),
                        ],
                        help_text="How clear and effective was our communication?",
                        verbose_name="Communication",
                    ),
                ),
                (
                    "what_did_well",
                    models.TextField(
                        blank=True,
                        help_text="Please share what you liked about our service",
                        verbose_name="What did we do well?",
                    ),
                ),
                (
                    "what_can_improve",
                    models.TextField(
                        blank=True,
                        help_text="Please share areas where we can do better",
                        verbose_name="What can we improve?",
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(
                        blank=True,
                        help_text="Any other feedback you would like to share",
                        verbose_name="Additional Comments",
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        default=True,
                        help_text="Would you recommend our services to others?",
                        verbose_name="Would you recommend us?",
                    ),
                ),
                (
                    "likelihood_to_use_again",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        default=10,
                        help_text="How likely are you to use our services again? (1=Not likely, 10=Very likely)",
                        verbose_name="Likelihood to Use Again (1-10)",
                    ),
                ),
                (
                    "submitted",
                    models.BooleanField(default=False, verbose_name="Submitted"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "feedback_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Feedback Request Sent At"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Internal Notes"),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="Follow-up Required"
                    ),
                ),
                (
                    "follow_up_completed",
                    models.BooleanField(
                        default=False, verbose_name="Follow-up Completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_feedback",
                        to="event_management.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_feedbacks_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Feedback",
                "verbose_name_plural": "Customer Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
