# Generated by Django 4.2.16 on 2025-11-05 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Token',
                'verbose_name_plural': 'SSO Tokens',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_url', models.URLField(max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sso.ssotoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_app_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Session',
                'verbose_name_plural': 'SSO Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('token_issued', 'Token Issued'), ('token_validated', 'Token Validated'), ('token_refreshed', 'Token Refreshed'), ('token_revoked', 'Token Revoked'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('permission_denied', 'Permission Denied')], max_length=50)),
                ('app_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Audit Log',
                'verbose_name_plural': 'SSO Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ssotoken',
            index=models.Index(fields=['jti', 'is_active'], name='sso_ssotoke_jti_8d5f01_idx'),
        ),
        migrations.AddIndex(
            model_name='ssotoken',
            index=models.Index(fields=['user', 'is_active'], name='sso_ssotoke_user_id_ba0795_idx'),
        ),
        migrations.AddIndex(
            model_name='ssosession',
            index=models.Index(fields=['user', 'is_active'], name='sso_ssosess_user_id_954cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='ssosession',
            index=models.Index(fields=['token', 'is_active'], name='sso_ssosess_token_i_803dad_idx'),
        ),
        migrations.AddIndex(
            model_name='ssoauditlog',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='sso_ssoaudi_user_id_ca6c60_idx'),
        ),
        migrations.AddIndex(
            model_name='ssoauditlog',
            index=models.Index(fields=['event_type', '-created_at'], name='sso_ssoaudi_event_t_ee1fad_idx'),
        ),
    ]
