# Generated by Django 4.2.16 on 2025-11-18 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(help_text='Unique employee identification code', max_length=50, unique=True, verbose_name='Employee Code')),
                ('attendance_role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Administrator')], default='employee', max_length=50, verbose_name='Attendance Role')),
                ('work_schedule_start', models.TimeField(blank=True, help_text='e.g., 09:00', null=True, verbose_name='Work Start Time')),
                ('work_schedule_end', models.TimeField(blank=True, help_text='e.g., 18:00', null=True, verbose_name='Work End Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Profile',
                'verbose_name_plural': 'Attendance Profiles',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_clock_out_enabled', models.BooleanField(default=True, help_text='Automatically clock out employees at end of day', verbose_name='Auto Clock Out Enabled')),
                ('auto_clock_out_time', models.TimeField(default='23:59', help_text='Time to auto clock out (if not clocked out manually)', verbose_name='Auto Clock Out Time')),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Grace period for late clock-in', verbose_name='Grace Period (Minutes)')),
                ('max_work_hours_per_day', models.DecimalField(decimal_places=2, default=12.0, max_digits=4, verbose_name='Max Work Hours Per Day')),
                ('require_approval_for_adjustments', models.BooleanField(default=True, verbose_name='Require Approval for Adjustments')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance System Configuration',
                'verbose_name_plural': 'Attendance System Configuration',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(verbose_name='Clock In Time')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Clock Out Time')),
                ('clock_in_method', models.CharField(choices=[('auto_wifi', 'Auto WiFi'), ('manual', 'Manual'), ('admin_adjusted', 'Admin Adjusted'), ('auto_eod', 'Auto End of Day'), ('qr_code', 'QR Code')], default='auto_wifi', max_length=20, verbose_name='Clock In Method')),
                ('clock_out_method', models.CharField(blank=True, choices=[('auto_wifi', 'Auto WiFi'), ('manual', 'Manual'), ('admin_adjusted', 'Admin Adjusted'), ('auto_eod', 'Auto End of Day'), ('qr_code', 'QR Code')], max_length=20, null=True, verbose_name='Clock Out Method')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Hours')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('device_hostname', models.CharField(blank=True, max_length=255, verbose_name='Device Hostname')),
                ('is_adjusted', models.BooleanField(default=False, verbose_name='Is Adjusted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendanceprofile')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-clock_in'],
            },
        ),
        migrations.AddField(
            model_name='attendanceprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.department'),
        ),
        migrations.AddField(
            model_name='attendanceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttendanceAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_clock_in', models.DateTimeField(blank=True, null=True, verbose_name='Original Clock In')),
                ('new_clock_in', models.DateTimeField(blank=True, null=True, verbose_name='New Clock In')),
                ('original_clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Original Clock Out')),
                ('new_clock_out', models.DateTimeField(blank=True, null=True, verbose_name='New Clock Out')),
                ('reason', models.TextField(verbose_name='Adjustment Reason')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approvals_made', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name': 'Attendance Adjustment',
                'verbose_name_plural': 'Attendance Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_hostname', models.CharField(max_length=255, verbose_name='Device Hostname')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC Address')),
                ('device_type', models.CharField(default='desktop', help_text='desktop, laptop, mobile', max_length=50, verbose_name='Device Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='attendance.attendanceprofile')),
            ],
            options={
                'verbose_name': 'Client Device',
                'verbose_name_plural': 'Client Devices',
                'ordering': ['-last_seen'],
                'unique_together': {('profile', 'device_hostname')},
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['profile', '-clock_in'], name='attendance__profile_4ee9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['clock_in'], name='attendance__clock_i_e5c5dd_idx'),
        ),
    ]
